// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
<<<<<<< HEAD
    apiKey: 'AIzaSyBTBU42KsfUJw00gwKx791T2fJ5Hz5z2Qk',
    appId: '1:661793489539:web:3a64c0cf75bd6922aed1b6',
    messagingSenderId: '661793489539',
    projectId: 'app-gamer-77b9f',
    authDomain: 'app-gamer-77b9f.firebaseapp.com',
    storageBucket: 'app-gamer-77b9f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiX1GrWllemCr_xKzlUHXWwCOI0Cu8P1I',
    appId: '1:661793489539:android:c0cb20d4767e0cf8aed1b6',
    messagingSenderId: '661793489539',
    projectId: 'app-gamer-77b9f',
    storageBucket: 'app-gamer-77b9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgCWrXhrmRNOWCTwsQfGaUZZ_8hROE2OM',
    appId: '1:661793489539:ios:086b6b2897f351c3aed1b6',
    messagingSenderId: '661793489539',
    projectId: 'app-gamer-77b9f',
    storageBucket: 'app-gamer-77b9f.firebasestorage.app',
=======
    apiKey: 'AIzaSyDXNrI88YTryRjxZfMwIU08ib287ZawS3Q',
    appId: '1:537428888311:web:593d6e66cf0c0c4585a1f2',
    messagingSenderId: '537428888311',
    projectId: 'appmprueba2vacunacion',
    authDomain: 'appmprueba2vacunacion.firebaseapp.com',
    storageBucket: 'appmprueba2vacunacion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDao_gj91XP2mS0S5KLqkgEeP53bZqMIQ4',
    appId: '1:537428888311:android:ae30b2f16158d71685a1f2',
    messagingSenderId: '537428888311',
    projectId: 'appmprueba2vacunacion',
    storageBucket: 'appmprueba2vacunacion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3p6VS6EXVXaPXO_jgTyOSFPkLAPv8ZI',
    appId: '1:537428888311:ios:6ff131968422bac285a1f2',
    messagingSenderId: '537428888311',
    projectId: 'appmprueba2vacunacion',
    storageBucket: 'appmprueba2vacunacion.firebasestorage.app',
>>>>>>> 995c9c65256ce180a209a398c9ec485d6b33e958
    iosBundleId: 'com.vacunacion.RG.vacunacionApp',
  );
}
