// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXNrI88YTryRjxZfMwIU08ib287ZawS3Q',
    appId: '1:537428888311:web:593d6e66cf0c0c4585a1f2',
    messagingSenderId: '537428888311',
    projectId: 'appmprueba2vacunacion',
    authDomain: 'appmprueba2vacunacion.firebaseapp.com',
    storageBucket: 'appmprueba2vacunacion.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDao_gj91XP2mS0S5KLqkgEeP53bZqMIQ4',
    appId: '1:537428888311:android:ae30b2f16158d71685a1f2',
    messagingSenderId: '537428888311',
    projectId: 'appmprueba2vacunacion',
    storageBucket: 'appmprueba2vacunacion.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe3p6VS6EXVXaPXO_jgTyOSFPkLAPv8ZI',
    appId: '1:537428888311:ios:6ff131968422bac285a1f2',
    messagingSenderId: '537428888311',
    projectId: 'appmprueba2vacunacion',
    storageBucket: 'appmprueba2vacunacion.firebasestorage.app',
    iosBundleId: 'com.vacunacion.RG.vacunacionApp',
  );
}
